name: extended_icon_button
description: "Extends the IconButton widget and adds support for long presses and holds."
version: 0.3.0
homepage: https://github.com/sharpsan/extended_icon_button

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
